### PR TITLE
Adds support to some more base elements in the language

### PR DESCRIPTION
**Pull request by ghyatzo**
Hello,

I've been working more on the syntax in these days, adding some more support to the basic elements of the language.
Main additions and changes:
- made number matching more solid
- rearranged some scopes for keywords and operators
- added some basic language pattern matching (for, as, class, lambdas, functions and others)
- added support to custom strings (`#" \\\ """ "#`) and correctly matching escaping and interpolations within
- Complete Types matching
- property vs object matching

There are still many more things to do and some immediate fixes to be done (like better variable declaration matching) but it is a good amout for a first PR! I'll keep adding modifications to this PR in the mean time

Also, deciding scopes is very hard and what might look ok on my color-scheme might look wrong on yours. Let me know.

PS: I am available to help mantain this package is needed :)

### CODE REVIEW

**Comment by serjan-nasredin** [comment]
Hello @ghyatzo, thanks for the PR! ❤️

**Comment by serjan-nasredin** [comment]
I don't understand why you removed the symbol highlighting? I thought it would be better to highlight them as strings.
image

Wouldn't it be better to do it like this?
image
image
This one is yours:
image

I think it's better to add `new` for the keyword, so that "YamlRenderer" and others are also highlighted with `entity.name.class.pkl`.
image

Aren't these operators?
image
The highlight `?*` I think they will be superfluous.

**Comment by ghyatzo** [comment]
Regarding the symbol: I saw from the language reference (and the syntax on the page) that quoted identifiers are not really strings and are not highlighted as such. 
So I opted for following the example on the page. I did scope them differently than other symbols anyway so they could be styled if needed.

Regarding the class scoping: yes you are completely correct. I am just now going through some of the scoping definitions to make them more consistent. I already made that change locally. Will commit it soon.

**Comment by ghyatzo** [comment]
I am currently also improving the typing matching since it had some wonky behaviors before.
Still have to add type constraint matching and function parameters parsing, already in my todo list.
Next I wanted to add some meta scopes to match object bodies and such!

**Comment by serjan-nasredin** [comment]
> Regarding the symbol: I saw from the language reference (and the syntax on the page) that quoted identifiers are not really strings and are not highlighted as such.

If these are variables, then I think it's better to highlight them as variables, but it's better not to highlight the ` characters themselves.

**Comment by serjan-nasredin** [comment]
image
The `module` keyword is highlighted as a variable.

**Comment by ghyatzo** [comment]
regarding `?` and `*` in the context of read and import being operators I am not completely sure.  I believe the `?` and `*` are valid "operators" only in the context of `read` and `import`  [the language reference ](https://pkl-lang.org/main/current/language-reference/index.html#nullable-reads) treats them as specific separate functions.

**Comment by ghyatzo** [comment]
> image The `module` keyword is highlighted as a variable.

yes, it is currently scoped as a `variable.language.pkl` so a "reserved" kind of keyword (`this`, `self`, `super` this kind of stuff). I roughly followed the sublime scope naming page but proper categorization will need to be discussed.

**Comment by serjan-nasredin** [comment]
> I believe the ? and * are valid "operators"

Acceptable, but not basic. because of this, I consider them as an operator.

**Comment by serjan-nasredin** [comment]
> `this`, `self`, `super` this kind of stuff

Such built-in functions in Python syntax highlighting are like this:
image

But in our case, if this keyword connects modules from the outside, then I think highlighting `keyword.pkl` will suit them.

**Comment by serjan-nasredin** [comment]
> ..but it is a good amout for a first PR!

LGTM

**Comment by ghyatzo** [comment]
> > I believe the ? and * are valid "operators"
> 
> Acceptable, but not basic. because of this, I consider them as an operator.

The official language reference highlights them together with the word, while in other cases (such as providing a default for a union type `*String|Bird` it does not, and in that case it could be an operator. 

Given that `?` and `*` apply as modifiers to only `read` and `import` functions I would more towards treating them as different versions of the same function, more than an operator that acts on a function. Otherwise the syntax would suggest that you could write something like `isBetween*(0, 300)` which is invalid.

**Comment by ghyatzo** [comment]
> > `this`, `self`, `super` this kind of stuff
> 
> Such built-in functions in Python syntax highlighting are like this: 
> 
> But in our case, if this keyword connects modules from the outside, then I think highlighting `keyword.pkl` will suit them.

agreed on having module as a keyword!

Another rather big task is to somehow recognize and highlight built in functions like `isBetween`, `xor` and the likes.
can't think of any other way other than huge lists

PS: it would be more helpful to know the scope name of the highlights other than the color, since that is color-scheme dependent (you can check the scope under the cursor using <kbd>ctrl<em>-</em>alt<em>-</em>shift<em>-</em>p</kbd> on windows or <kbd>⌘<em>-</em>shift<em>-</em>p</kbd> on macos)

**Comment by serjan-nasredin** [comment]
> Another rather big task is to somehow recognize and highlight built in functions like isBetween, xor and the likes.
can't think of any other way other than huge lists.

Can you show me an example?

> PS: it would be more helpful to know the scope name of the highlights other than the color, since that is color-scheme dependent (you can check the scope under the cursor using ctrl-alt-shit-P on windows or ctrl-shift-P on macos)

image

**Comment by ghyatzo** [comment]
> > Another rather big task is to somehow recognize and highlight built in functions like isBetween, xor and the likes.
> > can't think of any other way other than huge lists.
> 
> Can you show me an example?

something like: 
```
build-in: 
  - match: '\b(?:abs|abs2|abspath|accumulate|accumulate!|acos|acosd...
```
Maybe such lists can be generated automatically through pkl though. doing it by hand feels like madness.

**Comment by serjan-nasredin** [comment]
Add some built-in functions like `print` in Python, in the future, we'll see how it goes. :)

No need to add everything.

**Comment by serjan-nasredin** [comment]
image

**Comment by serjan-nasredin** [comment]
Would it be wrong to highlight as variables `var:`? `=|:`
image

**Comment by ghyatzo** [comment]
> Would it be wrong to highlight as variables `var:`? `=|:`

I am not sure I understood that sorry.

**Comment by ghyatzo** [comment]
Another big batch of improvements, we should cover most things now.
It is just a matter of bringing consistency to the scoping and add the standard library symbols (probably with a `support.*.pkl` scope, similarly to how the `print` function is scoped in python

**Comment by serjan-nasredin** [comment]
LGTM

@ghyatzo, thanks for the PR! ❤️

**Comment by ghyatzo** [comment]
My pleasure, thanks for making the package so quickly!

**Pull request merged**
